name: Playwright .NET NUnit Tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Install Playwright CLI and Browsers
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          playwright install --with-deps

      - name: Run NUnit Tests (generate TRX)
        run: dotnet test ./SwagLabs.Tests/SwagLabs.Tests.csproj --logger "trx;LogFileName=test-results.trx" --results-directory TestResults

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Generate HTML Report from TRX
        run: |
          reportgenerator \
            -reports:TestResults/test-results.trx \
            -targetdir:TestResults/HtmlReport \
            -reporttypes:HtmlSummary

      - name: Upload HTML Test Report
        uses: actions/upload-artifact@v4
        with:
          name: NUnit Test Report
          path: TestResults/HtmlReport
