name: Playwright .NET Tests
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build solution
        run: dotnet build --configuration Release
      - name: Install Playwright CLI
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          playwright install --with-deps
      - name: Create test_results folder
        run: mkdir -p test_results
      - name: Run tests and generate TRX report
        run: dotnet test ./SwagLabs.Tests/SwagLabs.Tests.csproj --logger "trx;LogFileName=test_results/results.trx"
      - name: Check if TRX report was created
        run: |
          echo "Looking for TRX files..."
          find . -name "*.trx" -type f
          ls -la test_results/ || echo "No test_results folder"
      - name: Convert TRX to HTML
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: test_results/results.trx
          reporter: dotnet-trx
          output-to: test_results/results.html
      - name: Move HTML report to test_results
        run: |
          if [ -f "TestResults/results.trx" ]; then
            cp TestResults/results.trx test_results/results.trx
          elif [ -f "results.trx" ]; then
            cp results.trx test_results/results.trx
          else
            echo "TRX report not found in expected locations"
          fi
      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: NUnit HTML Report
          path: test_results/
          if-no-files-found: error
