name: Playwright .NET Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Install Playwright Browsers
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          playwright install --with-deps

      - name: Run Playwright Tests
        run: dotnet test --logger "trx;LogFileName=test-results.trx" --results-directory TestResults

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Generate HTML Report
        run: |
          reportgenerator \
            -reports:TestResults/test-results.trx \
            -targetdir:TestResults/Report \
            -reporttypes:Html

      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        with:
          name: TestReport
          path: TestResults/test-results.html
