name: Playwright .NET NUnit Tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Install Playwright Browsers
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          playwright install --with-deps

      - name: Create test results directory
        run: mkdir -p test_results

      - name: Run Tests and Generate NUnit XML Results
        run: dotnet test ./SwagLabs.Tests/SwagLabs.Tests.csproj --logger "nunit;LogFilePath=test_results/results.xml"

      - name: Generate HTML test report
        uses: rjtngit/nunit-html-action@v1
        if: always()
        with:
          inputXmlPath: test_results/results.xml
          outputHtmlPath: test_results/results.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: NUnit HTML Test Report
          path: test_results/results.html
