name: Playwright .NET Tests
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build solution
        run: dotnet build --configuration Release
      - name: Install Playwright CLI
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          playwright install --with-deps
      - name: Create test_results folder
        run: mkdir -p test_results
      - name: Run tests and generate HTML report
        run: dotnet test ./SwagLabs.Tests/SwagLabs.Tests.csproj --logger "html;LogFileName=results.html"
      - name: Check if HTML report was created
        run: |
          echo "Looking for HTML files..."
          find . -name "*.html" -type f
          ls -la TestResults/ || echo "No TestResults folder"
          ls -la test_results/ || echo "No test_results folder"
      - name: Move HTML report to test_results
        run: |
          if [ -f "TestResults/results.html" ]; then
            cp TestResults/results.html test_results/results.html
          elif [ -f "results.html" ]; then
            cp results.html test_results/results.html
          else
            echo "HTML report not found in expected locations"
          fi
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: NUnit HTML Report
          path: test_results/results.html
