name: Playwright .NET NUnit Tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Install Playwright Browsers
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          playwright install --with-deps

      - name: Run NUnit Tests and Save Result
        run: dotnet test ./SwagLabs.Tests/SwagLabs.Tests.csproj --results-directory TestResults --logger "nunit;LogFileName=test-results.xml"

      - name: Install NUnit2HTML
        run: dotnet tool install --global nunit2html

      - name: Generate HTML Report from NUnit XML
        run: nunit2html TestResults/test-results.xml TestResults/test-results.html

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: NUnit HTML Test Report
          path: TestResults/test-results.html
