name: Playwright .NET Tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Install Playwright CLI and browsers
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          playwright install --with-deps

      - name: Run Playwright Tests
        run: dotnet test ./SwagLabs.Tests/SwagLabs.Tests.csproj --logger "trx;LogFileName=test-results.trx" --results-directory TestResults

      - name: Install trx2html
        run: dotnet tool install --global trx2html

      - name: Generate HTML Report from TRX
        run: |
          mkdir -p TestResults/Report
          trx2html TestResults/test-results.trx TestResults/Report/index.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: TestReport
          path: TestResults/Report
